from slList_stu import *
from dna_stu import *



"""
dnaList=constructDnaList("ATCGATCGATGC")
dnaList2=constructDnaList("TATAGCGCATGC")
dnaList3=constructDnaList("ATATCGCGTACG")
dnaList4=constructDnaList("TAGCTAGCTACG")
print(convertDnaListToString(dnaList))
print(convertDnaListToString(dnaList2))
print(convertDnaListToString(dnaList3))
print(convertDnaListToString(dnaList4))
print("Is list1 a pair for list2?",isPairing(dnaList,dnaList2))
print("Is list1 a pair for list3?",isPairing(dnaList,dnaList3))
print("Is list2 a pair for list3?",isPairing(dnaList2,dnaList3))
print("Is list1 a pair for list4?",isPairing(dnaList,dnaList4))
print("Is list2 a pair for list4?",isPairing(dnaList2,dnaList4))
print("Is list3 a pair for list4?",isPairing(dnaList3,dnaList4))
"""




print("Create a SlList (createList())")
myList=createList()
print()
print("Adding elements to the list:")
#print("append() and toString()")
append(myList,"data0")
#print(toString(myList))
append(myList,"data1")
#print(toString(myList))
append(myList,"data2")
#print(toString(myList))
append(myList,"data3")
#print(toString(myList))
append(myList,"data4")
#print(toString(myList))
append(myList,"data5")
#print(toString(myList))
append(myList,"data6")
#print(toString(myList))
append(myList,"data7")
print(toString(myList))
print()
#print("Inserting a new node at index 5 (insertAt())")
#insertAt(myList,5,100)
#print(toString(myList))
#print()
#print("Finding the element of the node with an index of 7. get()")
#print(get(myList,7))
#print()
#print("Setting the element at index 5 to data4.5. set()")
#set(myList,5,"data4.5")
#print(toString(myList))
#print()
#print("Popping the element at index 6. pop()")
#print("popped:",pop(myList,6))
#print(toString(myList))
#print()
"""
print("Finding the index of the element with a value data3. index()")
print("data3 found at index:",index(myList,"data3"))
print()
print("******************************\nInserting a new element at index 5. insertListAt()")
print("create a list to copy from:")
myList2=createList()
append(myList2,"dataZ")
append(myList2,"dataY")
append(myList2,"dataX")
append(myList2,"dataC")
append(myList2,"dataB")
append(myList2,"dataA")
print("List1=",toString(myList))
print("List2=",toString(myList2))
print()
insertListAt(myList,4,myList2)
print("myList=",toString(myList))
print()
"""
print("Deleting a 3-element segment starting from index 3")
print("myList before:",toString(myList))
deleteSegment(myList,2,2)
print("myList after:",toString(myList))
"""
print()
print("Copying a 4-element segment from index 1")
print("myList before:",toString(myList))
copySegment(myList,1,4)
print("myList after:",toString(myList))
"""


